apiVersion: apps/v1
kind: Deployment
metadata:
    name: exercise-app1-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
          app: exercise-app1            
    template:
        metadata:
            labels:
              app: exercise-app1
        spec:
          containers:
          - name: exercise-app1
            image: exercise-app1
            imagePullPolicy: IfNotPresent